import GreenEgg from '../img/Eggs/GreenEgg.png';
import BlueEgg from '../img/Eggs/BlueEgg.png';
import YellowEgg from '../img/Eggs/YellowEgg.png';
import PinkEgg from '../img/Eggs/PinkEgg.png';

export const careTags = ['Care', 'Weight', 'Happiness', 'Discipline', 'Battles', 'Techniques'];

export const statsTags = ['HP', 'MP', 'Offense', 'Defense', 'Speed', 'Brains'];

export const digimonsEggs = [
  {
    digimon: 'Green spotted egg',
    digivolvesTo: 'Botamon',
    image: GreenEgg,
    imageTo: '',
    careRequirements: {
      care: '',
      weight: '',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '',
      defense: '',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Blue lined egg',
    digivolvesTo: 'Punimon',
    image: BlueEgg,
    imageTo: '',
    careRequirements: {
      care: '',
      weight: '',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '',
      defense: '',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Yellow double lines egg',
    digivolvesTo: 'Poyomon',
    image: YellowEgg,
    imageTo: '',
    careRequirements: {
      care: '',
      weight: '',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '',
      defense: '',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Pink spotted egg',
    digivolvesTo: 'Yuramon',
    image: PinkEgg,
    imageTo: '',
    careRequirements: {
      care: '',
      weight: '',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '',
      defense: '',
      speed: '',
      brains: '',
    },
  },
];

export const digimonsFresh = [
  {
    digimon: 'Botamon',
    digivolvesTo: 'Koromon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '',
      weight: '',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '',
      defense: '',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Punimon',
    digivolvesTo: 'Tsunomon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '',
      weight: '',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '',
      defense: '',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Poyomon',
    digivolvesTo: 'Tokomon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '',
      weight: '',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '',
      defense: '',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Yuramon',
    digivolvesTo: 'Tanemon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '',
      weight: '',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '',
      defense: '',
      speed: '',
      brains: '',
    },
  },
];

export const digimonsInTraining = [
  {
    digimon: 'Koromon',
    digivolvesTo: 'Agumon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥0',
      weight: '10 - 20',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '',
      special: 'Offense must be at the highest stat and 10% of max HP.',
    },
    statsRequirements: {
      hp: '10',
      mp: '10',
      offense: '1',
      defense: '',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Koromon',
    digivolvesTo: 'Gabumon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥0',
      weight: '10 - 20',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥0',
      special: 'Defense or Speed must be at the highest stat',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '',
      defense: '1',
      speed: '1',
      brains: '',
    },
  },
  {
    digimon: 'Tokomon',
    digivolvesTo: 'Patamon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥0',
      weight: '10 - 20',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥0',
      special: 'Offense or Brains most be at teh highest stat and 10% of max HP',
    },
    statsRequirements: {
      hp: '10',
      mp: '',
      offense: '1',
      defense: '',
      speed: '',
      brains: '1',
    },
  },
  {
    digimon: 'Tokomon',
    digivolvesTo: 'Biyomon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥0',
      weight: '10 - 20',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥0',
      special: 'Speed must be at the highest stat and 10% of max HP.',
    },
    statsRequirements: {
      hp: '',
      mp: '10',
      offense: '',
      defense: '1',
      speed: '1',
      brains: '',
    },
  },
  {
    digimon: 'Tanemon',
    digivolvesTo: 'Palmon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥0',
      weight: '10 - 20',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥0',
      special: 'Brains must be at the highest stat and 10% of max HP.',
    },
    statsRequirements: {
      hp: '',
      mp: '10',
      offense: '',
      defense: '',
      speed: '1',
      brains: '1',
    },
  },
  {
    digimon: 'Tanemon',
    digivolvesTo: 'Betamon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥0',
      weight: '10 - 20',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥0',
      special: 'Defense must be at the highest stat and 10% of max HP.',
    },
    statsRequirements: {
      hp: '10',
      mp: '10',
      offense: '',
      defense: '1',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Tsunomon',
    digivolvesTo: 'Elecmon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥0',
      weight: '10 - 20',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥0',
      special: 'Offense or Speed must be at the highest stat.',
    },
    statsRequirements: {
      hp: '10',
      mp: '',
      offense: '1',
      defense: '',
      speed: '1',
      brains: '',
    },
  },
  {
    digimon: 'Tsunomon',
    digivolvesTo: 'Penguinmon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥0',
      weight: '10 - 20',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥0',
      special: 'Brains or Defense must be at the highest stat.',
    },
    statsRequirements: {
      hp: '',
      mp: '10',
      offense: '',
      defense: '1',
      speed: '',
      brains: '1',
    },
  },
  {
    digimon: 'Kunemon',
    digivolvesTo: 'Kunemon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '',
      weight: '',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '',
      special: 'A 50% chance exist to a Digimon to digivolve into this when sleeping at "Kunemon´s Bed".',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '',
      defense: '',
      speed: '',
      brains: '',
    },
  },
];

export const digimonsRookie = [
  {
    digimon: 'Agumon',
    digivolvesTo: 'Greymon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤1',
      weight: '25 - 35',
      happiness: '',
      discipline: '≥90',
      battles: '',
      techniques: '≥35',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '100',
      defense: '100',
      speed: '100',
      brains: '100',
    },
  },
  {
    digimon: 'Agumon',
    digivolvesTo: 'Meramon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥5',
      weight: '15 - 25',
      happiness: '',
      discipline: '',
      battles: '≥10',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '100',
      defense: '',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Agumon',
    digivolvesTo: 'Birdramon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥3',
      weight: '15 - 25',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥35',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '',
      defense: '',
      speed: '100',
      brains: '',
    },
  },
  {
    digimon: 'Agumon',
    digivolvesTo: 'Centarumon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤3',
      weight: '25 - 35',
      happiness: '',
      discipline: '≥60',
      battles: '',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '',
      defense: '',
      speed: '',
      brains: '100',
    },
  },
  {
    digimon: 'Agumon',
    digivolvesTo: 'Monochromon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤3',
      weight: '35 - 45',
      happiness: '',
      discipline: '',
      battles: '≤5',
      techniques: '≥35',
      special: 'Any Rookie Digimon can digivolve to Monochromon when its discipline gauge at 100% and a Defense +500',
    },
    statsRequirements: {
      hp: '1000',
      mp: '',
      offense: '',
      defense: '100',
      speed: '',
      brains: '100',
    },
  },
  {
    digimon: 'Agumon',
    digivolvesTo: 'Tyrannomon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤5',
      weight: '	25 - 35',
      happiness: '',
      discipline: '',
      battles: '≤5',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '1000',
      mp: '',
      offense: '',
      defense: '100',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Gabumon',
    digivolvesTo: 'Centarumon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤3',
      weight: '25 - 35',
      happiness: '',
      discipline: '≥60',
      battles: '',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '',
      defense: '',
      speed: '',
      brains: '100',
    },
  },
  {
    digimon: 'Gabumon',
    digivolvesTo: 'Monochromon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤3',
      weight: '35 - 45',
      happiness: '',
      discipline: '',
      battles: '≤5',
      techniques: '≥35',
      special: 'Any Rookie Digimon can digivolve to Monochromon when its discipline gauge at 100% and a Defense +500',
    },
    statsRequirements: {
      hp: '1000',
      mp: '',
      offense: '',
      defense: '100',
      speed: '',
      brains: '100',
    },
  },
  {
    digimon: 'Gabumon',
    digivolvesTo: 'Tyrannomon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤5',
      weight: '	25 - 35',
      happiness: '',
      discipline: '',
      battles: '≤5',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '1000',
      mp: '',
      offense: '',
      defense: '100',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Gabumon',
    digivolvesTo: 'Drimogemon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥3',
      weight: '35 - 45',
      happiness: '≥50',
      discipline: '',
      battles: '',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '100',
      defense: '',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Gabumon',
    digivolvesTo: 'Ogremon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥5',
      weight: '25 - 35',
      happiness: '',
      discipline: '',
      battles: '≥15',
      techniques: '≥35',
      special: 'Brains or Defense must be at the highest stat.',
    },
    statsRequirements: {
      hp: '1000',
      mp: '',
      offense: '100',
      defense: '',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Gabumon',
    digivolvesTo: 'Garurumon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤1',
      weight: '25 - 35',
      happiness: '',
      discipline: '≥90',
      battles: '',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '1000',
      offense: '',
      defense: '',
      speed: '100',
      brains: '',
    },
  },
  {
    digimon: 'Patamon',
    digivolvesTo: 'Tyrannomon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤5',
      weight: '	25 - 35',
      happiness: '',
      discipline: '',
      battles: '≤5',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '1000',
      mp: '',
      offense: '',
      defense: '100',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Patamon',
    digivolvesTo: 'Drimogemon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥3',
      weight: '35 - 45',
      happiness: '≥50',
      discipline: '',
      battles: '',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '100',
      defense: '',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Patamon',
    digivolvesTo: 'Ogremon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥5',
      weight: '25 - 35',
      happiness: '',
      discipline: '',
      battles: '≥15',
      techniques: '≥35',
      special: 'Brains or Defense must be at the highest stat.',
    },
    statsRequirements: {
      hp: '1000',
      mp: '',
      offense: '100',
      defense: '',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Patamon',
    digivolvesTo: 'Leomon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤1',
      weight: '15 - 25',
      happiness: '',
      discipline: '',
      battles: '≥10',
      techniques: '≥35',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '100',
      defense: '',
      speed: '100',
      brains: '100',
    },
  },
  {
    digimon: 'Patamon',
    digivolvesTo: 'Angemon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤0',
      weight: '15 - 25',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥35',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '1000',
      offense: '',
      defense: '',
      speed: '',
      brains: '100',
    },
  },
  {
    digimon: 'Patamon',
    digivolvesTo: 'Unimon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤3',
      weight: '25 - 35',
      happiness: '',
      discipline: '',
      battles: '≥10',
      techniques: '≥35',
      special: '',
    },
    statsRequirements: {
      hp: '1000',
      mp: '',
      offense: '',
      defense: '',
      speed: '100',
      brains: '',
    },
  },
  {
    digimon: 'Biyomon',
    digivolvesTo: 'Birdramon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥3',
      weight: '15 - 25',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥35',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '',
      defense: '',
      speed: '100',
      brains: '',
    },
  },
  {
    digimon: 'Biyomon',
    digivolvesTo: 'Airdramon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤1',
      weight: '25 - 35',
      happiness: '',
      discipline: '≥90',
      battles: '',
      techniques: '≥35',
      special:
        'A 30% chance exist to a Seadramon or Birdramon can Digivolve to Airdramon when they sleeps with discipline gauge at 100%, happiness at 100% and tiredness is at zero',
    },
    statsRequirements: {
      hp: '',
      mp: '1000',
      offense: '',
      defense: '',
      speed: '100',
      brains: '100',
    },
  },
  {
    digimon: 'Biyomon',
    digivolvesTo: 'Unimon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤3',
      weight: '25 - 35',
      happiness: '',
      discipline: '',
      battles: '≥10',
      techniques: '≥35',
      special: '',
    },
    statsRequirements: {
      hp: '1000',
      mp: '',
      offense: '',
      defense: '',
      speed: '100',
      brains: '',
    },
  },
  {
    digimon: 'Biyomon',
    digivolvesTo: 'Kokatorimon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥3',
      weight: '25 - 35',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '1000',
      mp: '',
      offense: '',
      defense: '',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Biyomon',
    digivolvesTo: 'Kabuterimon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤1',
      weight: '25 - 35',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥35',
      special: '',
    },
    statsRequirements: {
      hp: '1000',
      mp: '1000',
      offense: '100',
      defense: '',
      speed: '100',
      brains: '',
    },
  },
  {
    digimon: 'Palmon',
    digivolvesTo: 'Kuwagamon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥5',
      weight: '25 - 35',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '1000',
      mp: '1000',
      offense: '100',
      defense: '',
      speed: '100',
      brains: '',
    },
  },
  {
    digimon: 'Palmon',
    digivolvesTo: 'Vegiemon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥5',
      weight: '5 - 15',
      happiness: '≥50',
      discipline: '',
      battles: '',
      techniques: '≥21',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '1000',
      offense: '',
      defense: '',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Palmon',
    digivolvesTo: 'Palmon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤1',
      weight: '5 - 15',
      happiness: '',
      discipline: '',
      battles: '≥15',
      techniques: '≥35',
      special:
        'A Vegiemon has 30% to Digivolve to Ninjamon after fighting 50+ battles and its discipline gauge is at 100%',
    },
    statsRequirements: {
      hp: '',
      mp: '1000',
      offense: '100',
      defense: '',
      speed: '100',
      brains: '',
    },
  },
  {
    digimon: 'Palmon',
    digivolvesTo: 'Whamon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤5',
      weight: '35 - 45',
      happiness: '',
      discipline: '≥60',
      battles: '',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '1000',
      mp: '',
      offense: '',
      defense: '',
      speed: '',
      brains: '100',
    },
  },
  {
    digimon: 'Palmon',
    digivolvesTo: 'Palmon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '	≥3',
      weight: '25 - 35',
      happiness: '',
      discipline: '',
      battles: '≤5',
      techniques: '≥35',
      special:
        'A Whamon or Shellmon has 30% to Digivolve to Coelamon when 360 hours has passed since Digivolve from Champion form',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '',
      defense: '100',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Penguinmon',
    digivolvesTo: 'Garurumon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤1',
      weight: '25 - 35',
      happiness: '',
      discipline: '≥90',
      battles: '',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '1000',
      offense: '',
      defense: '',
      speed: '100',
      brains: '',
    },
  },
  {
    digimon: 'Penguinmon',
    digivolvesTo: 'Whamon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤5',
      weight: '35 - 45',
      happiness: '',
      discipline: '≥60',
      battles: '',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '1000',
      mp: '',
      offense: '',
      defense: '',
      speed: '',
      brains: '100',
    },
  },
  {
    digimon: 'Elecmon',
    digivolvesTo: 'Leomon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤1',
      weight: '15 - 25',
      happiness: '',
      discipline: '',
      battles: '≥10',
      techniques: '≥35',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '100',
      defense: '',
      speed: '100',
      brains: '100',
    },
  },
  {
    digimon: 'Elecmon',
    digivolvesTo: 'Angemon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤0',
      weight: '15 - 25',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥35',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '1000',
      offense: '',
      defense: '',
      speed: '',
      brains: '100',
    },
  },
  {
    digimon: 'Elecmon',
    digivolvesTo: 'Kokatorimon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥3',
      weight: '25 - 35',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '1000',
      mp: '',
      offense: '',
      defense: '',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Betamon',
    digivolvesTo: 'Whamon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤5',
      weight: '35 - 45',
      happiness: '',
      discipline: '≥60',
      battles: '',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '1000',
      mp: '',
      offense: '',
      defense: '',
      speed: '',
      brains: '100',
    },
  },
  {
    digimon: 'Betamon',
    digivolvesTo: 'Betamon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '	≥3',
      weight: '25 - 35',
      happiness: '',
      discipline: '',
      battles: '≤5',
      techniques: '≥35',
      special:
        'A Whamon or Shellmon has 30% to Digivolve to Coelamon when 360 hours has passed since Digivolve from Champion form',
    },
    statsRequirements: {
      hp: '',
      mp: '',
      offense: '',
      defense: '100',
      speed: '',
      brains: '',
    },
  },
  {
    digimon: 'Kunemon',
    digivolvesTo: 'Kabuterimon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≤1',
      weight: '25 - 35',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥35',
      special: '',
    },
    statsRequirements: {
      hp: '1000',
      mp: '1000',
      offense: '100',
      defense: '',
      speed: '100',
      brains: '',
    },
  },
  {
    digimon: 'Kunemon',
    digivolvesTo: 'Kuwagamon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥5',
      weight: '25 - 35',
      happiness: '',
      discipline: '',
      battles: '',
      techniques: '≥28',
      special: '',
    },
    statsRequirements: {
      hp: '1000',
      mp: '1000',
      offense: '100',
      defense: '',
      speed: '100',
      brains: '',
    },
  },
  {
    digimon: 'Kunemon',
    digivolvesTo: 'Vegiemon',
    image: '',
    imageTo: '',
    careRequirements: {
      care: '≥5',
      weight: '5 - 15',
      happiness: '≥50',
      discipline: '',
      battles: '',
      techniques: '≥21',
      special: '',
    },
    statsRequirements: {
      hp: '',
      mp: '1000',
      offense: '',
      defense: '',
      speed: '',
      brains: '',
    },
  },
];
